[engine]
rows = 64
cols = 64
layers = 8
seed = 42
device = "cpu"

[phase4]
embed_dim = 64
similarity = "cosine"
alpha = 0.65
beta = 0.20
gamma = 0.10
delta = 0.05
mmr_lambda = 0.7
refresh_interval_steps = 500
drift_threshold = 0.08

[p5a]
predict_horizon = 2
features = ["coherence", "entropy", "grad_energy"]

[p5b]
dissonance_threshold = 0.25
actions = ["SeedFrom", "DampLR", "CoolTint", "PauseAug"]

[p5b.weights]
coherence = 0.5
entropy = 0.3
energy = 0.2

[p5c]
lr_damp_max = 0.5
cool_tint_max = 0.2
pause_aug_max_steps = 200
ethics_hue_jump_deg = 90
log_every = 1
